version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./DeepWebResearcher
      dockerfile: Dockerfile
    container_name: deepweb-researcher-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app_with_auth.py
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
    volumes:
      - ./DeepWebResearcher/research_database.sqlite:/app/research_database.sqlite
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - deepweb-network

  # Frontend
  frontend:
    build:
      context: ./ChatBot
      dockerfile: Dockerfile
    container_name: deepweb-researcher-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5001
      - VITE_APP_NAME=DeepWeb Researcher
      - VITE_APP_VERSION=1.0.0
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - deepweb-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: deepweb-researcher-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - deepweb-network
    profiles:
      - production

networks:
  deepweb-network:
    driver: bridge

volumes:
  logs:
    driver: local 