version: '3.8'

services:
  # Backend API (Development)
  backend:
    build:
      context: ./DeepWebResearcher
      dockerfile: Dockerfile
    container_name: deepweb-researcher-backend-dev
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app_with_auth.py
      - JWT_SECRET_KEY=dev-secret-key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
    volumes:
      - ./DeepWebResearcher:/app
      - ./DeepWebResearcher/research_database.sqlite:/app/research_database.sqlite
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "app_with_auth.py"]
    networks:
      - deepweb-network-dev

  # Frontend (Development)
  frontend:
    build:
      context: ./ChatBot
      dockerfile: Dockerfile.dev
    container_name: deepweb-researcher-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5001
      - VITE_APP_NAME=DeepWeb Researcher (Dev)
      - VITE_APP_VERSION=1.0.0-dev
      - VITE_DEV_MODE=true
    volumes:
      - ./ChatBot:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    command: ["npm", "run", "dev"]
    networks:
      - deepweb-network-dev

networks:
  deepweb-network-dev:
    driver: bridge

volumes:
  logs:
    driver: local 