[phases.setup]
nixPkgs = ["python3", "nodejs", "npm"]

[phases.install]
cmds = [
  "cd DeepWebResearcher && pip install -r requirements.txt",
  "cd ChatBot && npm install"
]

[phases.build]
cmds = [
  "cd ChatBot && npm run build"
]

[start]
cmd = "cd DeepWebResearcher && python app.py" 